
server:
  port: 8083

spring:
  application:
    name: spring-test
  datasource: # ?????
    name: local_test
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/local_test?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    password: root
    username: root
    hikari:
      maximum-pool-size: 15
      minimum-idle: 5
      auto-commit: true
      idle-timeout: 60000
      pool-name: hikariCP
      max-lifetime: 30000
      connection-test-query: SELECT 1
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 500
    lettuce:
      pool:
        max-wait: 16
        max-active: 100
        max-idle: 16
        min-idle: 1
      shutdown-timeout: 10000ms
    database: 0
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.waltz.springshirostudy.entity


logging:
  level:
    com.waltz.springshirostudy.mapper: debug


system.config.filterExclude: /swagger*,/webjars*,/v2/*,/favicon.ico,/druid*,/upload/*,/O2O_MENU/image/synImg*,/O2O_MENU/bso/*,/O2O_MENU/dicProductCategory/queryCategoryList